#Node.js image
FROM node:18

#Working directory inside container
WORKDIR /usr/src/app

#Copy package.json and package-lock.json
#COPY package*.json ./

#Install dependencies
#RUN npm install --silent

#Copy the apps source code
COPY . .

#Expose port app will run on
#EXPOSE 3000

#CMD ["npm", "start"]
#CMD ["echo", "React app container setup successful!"]
